# Generated by Django 4.2.29 on 2026-06-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cover_pic',
            field=models.ImageField(blank=True, null=True, upload_to='cover_pics/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cover_position',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cover_preset',
            field=models.CharField(default='nebula', max_length=50),
        ),
    ]
