# Generated by Django 4.2.29 on 2026-04-01 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectsubmission_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsubmission',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_submissions', to='courses.course'),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='total_marks',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
