# Generated by Django 4.2.29 on 2026-06-06 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_project_end_date_course_project_start_date'),
        ('recorded_classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordedclass',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recorded_classes', to='courses.course'),
        ),
    ]
