# Generated by Django 4.2.29 on 2026-03-31 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_test_score', models.PositiveIntegerField(default=0)),
                ('project_count', models.PositiveIntegerField(default=0)),
                ('overall_score', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('in_progress', 'In Progress')], default='in_progress', max_length=20)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_reports', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
