# Generated by Django 4.2.29 on 2026-06-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_results_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='project_end_date',
            field=models.DateTimeField(blank=True, help_text='End date/deadline for project submissions', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='project_start_date',
            field=models.DateTimeField(blank=True, help_text='Start date for project submissions', null=True),
        ),
    ]
