# Generated by Django 4.2.29 on 2026-06-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_aitutormessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='department_covers/'),
        ),
    ]
