# Generated by Django 4.2.29 on 2026-04-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='label',
            field=models.CharField(choices=[('assignment', 'Assignment'), ('test', 'Test'), ('project', 'Project')], default='assignment', help_text='Type: Assignment, Test, or Project', max_length=20),
        ),
    ]
