# Generated by Django 4.2.29 on 2026-04-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_submission_code_submission_alter_submission_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='code_submission',
        ),
        migrations.AddField(
            model_name='submission',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
