# Generated by Django 4.2.29 on 2026-03-31 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_results_released'),
        ('tests', '0002_test_available_from_test_end_date_test_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='courses.course'),
        ),
    ]
