# Generated by Django 4.2.29 on 2026-04-02 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_test_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('input_data', models.TextField(help_text='Use JSON array format for function arguments. Example: [[1, 2, 3]]')),
                ('expected_output', models.TextField(help_text='Expected return value in JSON format. Example: 6 or [1, 4, 9]')),
                ('is_sample', models.BooleanField(default=False, help_text='Sample tests are visible to students during practice runs.')),
                ('weight', models.PositiveIntegerField(default=1)),
                ('explanation', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['created_at', 'id']},
        ),
        migrations.AddField(
            model_name='question',
            name='expected_function_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Quiz / Multiple Choice'), ('coding', 'Coding Question')], default='mcq', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='starter_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentresponse',
            name='answers_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='studentresponse',
            name='coding_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='studentresponse',
            name='coding_submissions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='studentresponse',
            name='evaluation_summary',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='studentresponse',
            name='quiz_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(blank=True, choices=[('option1', 'Option 1'), ('option2', 'Option 2'), ('option3', 'Option 3'), ('option4', 'Option 4')], max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='option1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentresponse',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AddConstraint(
            model_name='studentresponse',
            constraint=models.UniqueConstraint(fields=('student', 'test'), name='unique_student_test_response'),
        ),
        migrations.AddField(
            model_name='codingtestcase',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='tests.question'),
        ),
    ]
