# Generated by Django 4.2.29 on 2026-06-06 17:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0004_codingtestcase_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, help_text='Select specific students to assign this to. Leave blank to assign to all enrolled students.', related_name='assigned_tests', to=settings.AUTH_USER_MODEL),
        ),
    ]
