# Generated by Django 4.2.29 on 2026-06-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_test_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='reference_solution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
