# Generated by Django 4.2.29 on 2026-06-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_question_reference_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresponse',
            name='retake_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentresponse',
            name='retake_requested',
            field=models.BooleanField(default=False),
        ),
    ]
